// Redux Global Action names

// GLOBAL
export const CLEAR_CACHE = 'CLEAR_CACHE';

// LISTS
export const LIST_LOAD = 'LIST_LOAD';
export const LIST_LOAD_REQUEST = 'LIST_LOAD_REQUEST';
export const LIST_LOAD_SUCCESS = 'LIST_LOAD_SUCCESS';
export const LIST_LOAD_ERROR = 'LIST_LOAD_ERROR';

export const LIST_CREATE = 'LIST_CREATE';
export const LIST_CREATE_REQUEST = 'LIST_CREATE_REQUEST';
export const LIST_CREATE_SUCCESS = 'LIST_CREATE_SUCCESS';
export const LIST_CREATE_ERROR = 'LIST_CREATE_ERROR';

export const LIST_RESET = 'LIST_RESET';
export const LIST_RESET_REQUEST = 'LIST_RESET_REQUEST';
export const LIST_RESET_SUCCESS = 'LIST_RESET_SUCCESS';
export const LIST_RESET_ERROR = 'LIST_RESET_ERROR';

// ITEMS
export const ITEM_CREATE = 'ITEM_CREATE';
export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST';
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';
export const ITEM_CREATE_ERROR = 'ITEM_CREATE_ERROR';

export const ITEM_DELETE = 'ITEM_DELETE';
export const ITEM_DELETE_REQUEST = 'ITEM_DELETE_REQUEST';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_ERROR = 'ITEM_DELETE_ERROR';

export const ITEM_REORDER = 'ITEM_REORDER';
export const ITEM_REORDER_REQUEST = 'ITEM_REORDER_REQUEST';
export const ITEM_REORDER_SUCCESS = 'ITEM_REORDER_SUCCESS';
export const ITEM_REORDER_ERROR = 'ITEM_REORDER_ERROR';
